### ISSUE TITLE
Test code coverage on jenkin

### ISSUE THREAD

**Issue by stevenhwu** [denovogear/denovogear#107]
Beside compile and run the tests on Jenkin, maybe we should calculate some sort of code coverage for each PR and pre-release.

Maybe something like
- [cobertura](https://wiki.jenkins-ci.org/display/JENKINS/Cobertura+Plugin)
- [gcovr/gcov](http://gcovr.com/guide.html)

Not sure what is the best way to store (if we want to) coverage report.

**Comment by reedacartwright** [comment]
I think we need to have a CMake option like `-DENABLE_TEST_COVERAGE=on` that will change the compiling options so that `make test` will generate coverage information.

**Comment by stevenhwu** [comment]
As far as I know, Cobertura is running on Jenkin already. What's next? @anderspitman

**Comment by anderspitman** [comment]
We haven't quite finished getting it up and running, but we're close.

**Comment by anderspitman** [comment]
@stevenhwu and I discovered unexpected behavior with the way we're currently doing coverage. Basically gcovr isn't counting source files that don't get run during the tests, so it's inflating our results. We managed to get "100% coverage" by running a single unit test. I'm working to track this down now.

**Comment by reedacartwright** [comment]
Resolved
