### ISSUE TITLE
make test gives false negative result for CALL_Sample5.3_VCF

### ISSUE THREAD

**Issue by stevenhwu** [denovogear/denovogear#110]
### Where

on develop branch, for `./test/CMakeLists.txt` at line 136-144. start with `ADD_TEST(CALL_Sample5.3_VCF ...`
Most likely somewhere else as well.
### How to reproduce it

if we change line 139-143 (first 5 line of PASS_REGULAR_EXPRESSION) to something crazy, i.e. replace 0/0 with 1/2 and append random characters.

```
SET_TESTS_PROPERTIES(CALL_Sample5.3_VCF PROPERTIES PASS_REGULAR_EXPRESSION "MUPXXX=XXX")
SET_TESTS_PROPERTIES(CALL_Sample5.3_VCF PROPERTIES PASS_REGULAR_EXPRESSION "1/20000:ZZZ")
SET_TESTS_PROPERTIES(CALL_Sample5.3_VCF PROPERTIES PASS_REGULAR_EXPRESSION "1/2:18:0.984574 AAA")
SET_TESTS_PROPERTIES(CALL_Sample5.3_VCF PROPERTIES PASS_REGULAR_EXPRESSION "1/2:9:0.868225 BBB")
SET_TESTS_PROPERTIES(CALL_Sample5.3_VCF PROPERTIES PASS_REGULAR_EXPRESSION "1/2:38:0.999837 CCC")
```

and run the test with 
`cd build/;rm -r *;cmake ..;make testdata;make dng-call; ctest -VV -R "CALL_Sample5.3_VCF$"`
It will pass the test with the following output

```
20: #CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  GL-1    GL-2    LB-NA12878:Solexa-135852    LB-NA12891:Solexa-135851    LB-NA12892:Solexa-135853
20: 5   126385924   .   G   T,C .   .   MUP=0.116189;LLD=-30.5967;LLH=-6.68014;MUX=0.116189;MU1P=0.116189;DNT=GGxGG>GT;DNL=LB-NA12878:Solexa-135852;DNQ=42;DNC=100;DP=189;AD=158,30,1   GT:GQ:GP:GL:DP:AD:MUP:MU1P  0/0:38:0.999833,0.000167058,1.78739e-12,2.75325e-11,3.57372e-16,4.51356e-20:.,.,.,.,.,.:.:.,.,.:.:. 0/0:18:0.984574,0.0154262,1.66835e-10,9.77602e-12,1.67414e-14,1.58815e-20:.,.,.,.,.,.:.:.,.,.:.:.   0/0:9:0.868225,0.131775,7.45988e-16,1.99601e-09,2.97932e-17,3.704e-26:-6.74046,0,-6.07991,-7.58973,-7.55553,-15.93:55:25,29,1:0.999933:0.999933 0/0:38:0.999837,0.000163186,2.11375e-15,2.7779e-11,4.22658e-19,5.33792e-23:0,-6.64246,-17.5301,-6.64246,-17.5301,-17.5301:57:57,0,0:3.33278e-05:3.33278e-05 0/0:18:0.984578,0.0154223,6.97054e-14,9.45085e-12,6.98069e-18,2.94856e-24:0,-4.667,-16.0119,-7.10524,-16.3122,-18.7879:77:76,1,0:3.33292e-05:3.33292e-05
1/1 Test #20: CALL_Sample5.3_VCF ...............   Passed    0.03 sec

The following tests passed:
    CALL_Sample5.3_VCF

100% tests passed, 0 tests failed out of 1
```
### What is working?

However, if you change line 144, the last line, it fails as expected.

```
SET_TESTS_PROPERTIES(CALL_Sample5.3_BAM PROPERTIES PASS_REGULAR_EXPRESSION "0/0:8:0.851097[0-9]*,0.148903[0-9]*,5.26064[0-9]*e-12:0,-3.86108[0-9]*,-14.313[0-9]*:56:55,1:22,0:33,1:3.3337[0-9]*e-05:3.3337[0-9]*e-05")
```
### Possible reason

When we have multiple `SET_TESTS_PROPERTIES(CALL_Sample5.3_VCF PROPERTIES PASS_REGULAR_EXPRESSION`, the last one is used.

**Comment by reedacartwright** [comment]
Look at https://github.com/Kitware/CMake/tree/master/Tests for examples of complicated tests.  I'm sure we will find something there that helps us.

**Comment by reedacartwright** [comment]
@kaeldai Do we have any good solutions for this?

**Comment by kaeldai** [comment]
Not really, cmake doesn't have any support for appending multiple properties together in an AND'd list. We need to create a function that wraps around set_properties().

**Comment by reedacartwright** [comment]
Then the solution is that we use a cmake script to call the binary and test that all the regexes pass.

See https://github.com/Kitware/CMake/blob/master/Tests/CMakeTestAllGenerators/RunCMake.cmake for inspiration.

**Comment by reedacartwright** [comment]
Progress is being made: https://github.com/reedacartwright/denovogear/tree/feature/issue-110
