### ISSUE TITLE
Build external on ubuntu doesn't support https

### ISSUE THREAD

**Issue by jgarciamesa** [denovogear/denovogear#123]
Run cmake with build externals on ubuntu with the default cmake fails to download packages for eigen and htslib because the use of https instead of http

**Comment by kaeldai** [comment]
Doesn't work when fetching cmake from the utopic library, or building cmake on ubuntu. The issue is with libcurl.

Will work when downloading and running the precompiled Linux x86_64 binary.

**Comment by reedacartwright** [comment]
Duplicate of #19
