### ISSUE TITLE
Information used from vcf file by dng dnm?

### ISSUE THREAD

**Issue by aistrand** [denovogear/denovogear#125]
Hi,

I would like to know which fields/information dng dnm uses from the input vcf file to determine which sites have putative mutations. I understand the program uses genotype likelihoods (and also read depth for filtering purposes). Genotype likelihoods are present in the FORMAT field for each individual. Are there any other fields that are used by your program/model?

Thanks,
Alva

**Comment by reedacartwright** [comment]
@gatoravi @dconrad, do you know?

**Comment by gatoravi** [comment]
Hi,
The model uses the PL field which contains the likelihoods, it also uses the depth and mapping quality fields for filtering.
Avi

**Comment by kaeldai** [comment]
DNM can also use the [I16 mapping qualities](http://samtools.sourceforge.net/mpileup.shtml), inserted as a list in the INFO field. However it's not required.

**Comment by aistrand** [comment]
OK great, thanks!

**Comment by aistrand** [comment]
What are the specific filtering criteria that are used for read depth (rd_cutoff) and mapping quality? Could not find specific values in your documentation.

**Comment by gatoravi** [comment]
When you run the program with no parameters you will see that the default read-depth cutoff is set to 10, this is the value within the parantheses, 

```
  -R [ --rd_cutoff ] arg (=10)       Read depth filter, sites where either one
                                     of the sample have read depth less than
                                     this threshold are filtered out
```

You can set this value to something else(same goes for --pp_cutoff). I think the mapping quality filter has been turned off for now.

**Comment by reedacartwright** [comment]
Alva, I think your question has been answered, so I will close this thread.

**Comment by aistrand** [comment]
Sure, thanks!

Alva

On Wed, Apr 6, 2016 at 9:06 PM, Reed A. Cartwright <notifications@github.com
