### ISSUE TITLE
VCF output not working in dng-dnm.

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#141]
Email from a user:

> I work on trios and am trying to use denovogear. The tools works perfectly, but since I plan to do annotations further, I would prefer to have the output in vcf format. For this, I used the --output_vcf option as below:
> 
> dng dnm auto --ped Fam01.ped --bcf Fam01.bcf --output_vcf Fam01_denovogear_output.vcf
> 
> but I get the message -unrecognised option '--output_vcf'. 
> 
> Then I tried using --vcf and -v options and I get this message: "ERROR ! Attempting to use both a vcf and bcf file, can only use one. Exiting !". 
> 
> Could you please let me know which option should I specify to get the output in vcf format?

**Comment by natepalmer** [comment]
Per `dng dnm --help`, --vcf / -v are for reading input from vcf; the appropriate option to use here is --write / -w. 
However, this seems to be broken.

```
$ dng dnm auto --ped ../trio.ped --bcf trio.bcf --write output.vcf

Created SNP lookup table
 First mrate: 1 last: 1
 First code: 6 last: 6
 First target string: AA/AA/AA last: TT/TT/TT
 First tref: 0.0002388 last: 0.99301

Created indel lookup table First code: 6 last: 6
 First target string: RR/RR/RR last: DD/DD/DD
 First prior: 0.05 last: 0.114

Created paired lookup table
 First target string: AA/AA last: TT/TT
 First prior 1 last: 1
DENOVO-SNP CHILD_ID: NA12878 chr: 5 pos: 126385924 ref: G alt: T,<*> maxlike_null: 1.50673e-14 pp_null: 1.59338e-06 tgt_null(child/mom/dad): GT/GG/GT snpcode: 2 code: 9 maxlike_dnm: 9.9301e-09 pp_dnm: 0.999998 tgt_dnm(child/mom/dad): GT/GG/GG lookup: 5 flag: 1 READ_DEPTH child: 35 dad: 34 mom: 44 MAPPING_QUALITY child: 0 dad: 0 mom: 0
Segmentation fault (core dumped)

```

**Comment by reedacartwright** [comment]
@kaeldai Can you recreate this segfault?
