### ISSUE TITLE
BOOST Floating point comparison

### ISSUE THREAD

**Issue by stevenhwu** [denovogear/denovogear#157]
Reed: We should make this configurable somehow from a CMake run. It is important to test both absolute equality and threshold-based equality.

Note: Boost provided three levels of check, so `<level>` is one of the following `{WARN, CHECK, REQUIRE}`
- For absolute equality, i.e. string/char, `BOOST_<level>` and `BOOST_<level>_EQUAL` should be sufficient for most of the cases.
- For [floating point comparison](http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/testing_tools/extended_comparison/floating_point.html), Boost offer several different options. The most useful one at this stage might be
  - For threshold tolerance and boost preferred method [`BOOST_<level>_CLOSE`](http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/assertion_boost_level_close.html) & [`BOOST_<level>_CLOSE_FRACTION`](http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/assertion_boost_level_close_fraction.html)
  - For the absolute tolerance [`BOOST_<level>_SMALL`](http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/assertion_boost_level_small.html). This can be useful as well for certain cases.

Currently, there are two `const` variable in `boost_test_helper.h`, and there are a few things we should address.
- [ ] What is the reasonable default values for these thresholds?
- [ ] When should we use absolute test?
- [ ] Ability to set/control these variable from CMake?

Note:
- These are available at [v55](http://www.boost.org/doc/libs/1_55_0/libs/test/doc/html/utf/testing-tools/reference.html) and [v61](http://www.boost.org/doc/libs/1_61_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref.html)
- The `tolerance (decorator)` is introduced at v59

An example:
`BOOST_CHECK_CLOSE(a, b, 1e-6)` -> Fail at difference{3.56834e-08} between expected.length1{3.0000000000000004e-08} and actual.length1{2.9999998929497451e-08} exceeds 1e-06%

**Comment by reedacartwright** [comment]
Fixed in #220.
