### ISSUE TITLE
<Eigen/Sparse> must be included to compile certain files due to changes in Eigen3.2.9

### ISSUE THREAD

**Issue by zmertens** [denovogear/denovogear#172]
The `<Eigen/Sparse>` header must be included before `<Eigen/KroneckerProduct>` in order to to compile `matrix.h`, `snpLike.cc`, `pairLike.cc`, and `indelLike.cc` files.

This issue appears to be a change started in the Eigen 3.2.9 libraries and persists in the latest package found in the Ubuntu xenial repositories. 
I tested:
- [Eigen 3.2.0-8 on Ubuntu 14.04 "trusty"](http://packages.ubuntu.com/trusty/libeigen3-dev) -- works
- [Eigen 3.2.5-4 on Ubuntu "wily"](http://packages.ubuntu.com/wily/libeigen3-dev) -- works
- [Eigen 3.3~beta1-2 on Ubuntu "xenial"](http://packages.ubuntu.com/xenial/libeigen3-dev) -- doesn't work

I talked with @kaeldai and he noted not to put up a pull request until Jenkins is happy. I created a branch to address the change [here](https://github.com/zryan3/denovogear/tree/172-Eigen3-regression).

**Comment by kaeldai** [comment]
Once I'm able to I will create a test machine with Eigen 3.2.9. @zryan3, what version of Mint were you using?

**Comment by zmertens** [comment]
@kaeldai 17.3

**Comment by kaeldai** [comment]
Zach, can you do a pull request. We have a [jenkins test machine with Mint that is running into the same issue](http://jenkins.cartwrig.ht/job/DeNovoGear/label=Mint/117/console).
