### ISSUE TITLE
bcfdata is unnecessarily a vector

### ISSUE THREAD

**Issue by anderspitman** [denovogear/denovogear#198]
[See here](https://github.com/denovogear/denovogear/blob/36bbe9970266389a8a66a5887502fa418e05c45f/src/lib/task/call.cc#L245)

Is there a reason for this? As near as I can tell only the first index is ever used, and it's use is hard coded.

**Comment by kaeldai** [comment]
Because we can't initialize a bcf:File object without a bcf file, which we won't have if the user passes in bam files, we need a wrapper or use a (smart) pointer. I used a vector as a wrapper because in the future we may want handle multiple vcf files like gatk does.

**Comment by kaeldai** [comment]
This is no longer relevant. Issue #204 removed the use of a vector for bcfdata.
