### ISSUE TITLE
Use EXT_DEPS variable in ExternalDep.cmake for Zlib and Boost path prefixes

### ISSUE THREAD

**Issue by zmertens** [denovogear/denovogear#200]
In the `denovogear/Modules/ExternalDep.cmake` file, the Boost and Zlib PREFIX paths in the `ExternalProject_add` macro is hardcoded and not using the CMake variable, `EXT_PREFIX`, which is set at the top of the CMake file. This could potentially lead to path error if the prefix is (ever) changed someday.

_Recommended solution:_
- [line 100] `PREFIX ext_deps/zlib` --> `PREFIX "${EXT_PREFIX}/zlib"`
- [line 218] `PREFIX ext_deps/boost` --> `PREFIX "${EXT_PREFIX}/boost"`

**Comment by stevenhwu** [comment]
Do you mind create a pull request for this? 
This make sense to me and it's used for Eigen3 and htslib already

**Comment by zmertens** [comment]
Fixed by #201
