### ISSUE TITLE
dng-loglike, dng-call, dng-pileup segfaults on bam

### ISSUE THREAD

**Issue by kaeldai** [denovogear/denovogear#209]
Using command
./src/dng-loglike -p ~/testdata/sample_5_3/ceu.ped ~/testdata/sample_5_3/test1.bam

Creates most of the vcf header but missing #contig and column labels. Also fails with test1.sam

**Comment by kaeldai** [comment]
In loglike.cc process_bam, call to h->target_name[contig] is throwing a segmentation fault. Likely it is due to the fact that the "##contig" line has not yet been set.

**Comment by jgarciamesa** [comment]
The error is thrown because in case a bam/sam/cram file is given it must be checked that also a fasta file is provided, otherwise there is no reference data.
