### ISSUE TITLE
DNG Call PL field

### ISSUE THREAD

**Issue by stevenhwu** [denovogear/denovogear#217]
`dng call` gets `Segmentation fault (core dumped)` when PL is used.
- Implement warning/debugging message.

```
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="List of Phred-scaled genotype likelihoods">
```

Thanks @cryancampbell

**Comment by jgarciamesa** [comment]
Seems like the issue has been solved by the latest updates to the develop branch. Now `dng call` when using PL tag on a `VCF` file does not throw a `Segmentation fault` error message. However, if you could double check it I would appreciate it @stevenhwu .

**Comment by reedacartwright** [comment]
See #236.
