### ISSUE TITLE
DenovoGear v1.1.1 run didn't call any denovo insertions

### ISSUE THREAD

**Issue by simonzzc034** [denovogear/denovogear#249]
I recently run your tool on 10K+ trios.  There were denovo SNVs, deletions called, but not a single denovo insertion was called. Any insight why that could have happened? Thanks!

**Comment by reedacartwright** [comment]
Please post the command line you used to call mutations. Some of the tools do not yet support indel calling.

**Comment by simonzzc034** [comment]
I used GATK HC to get gvcf files on the samples, then get the variant called in a VCF format using GATK joint genotyping on the gvcf. The VCF files, which contained SNVs and INDELs,  were then input to your tool. But I just noticed that the "Phred-scaled genotype likelihoods" from GATK is very different than these from Samtools mpileup and that messed up things I guess since that's the main thing your tool uses.

**Comment by reedacartwright** [comment]
I assume that you used `dng dnm` then?  I am working to make `dng call` compatible with both GATK and Samtools genotype likelihoods.

**Comment by simonzzc034** [comment]
That's right. I was under the impression that you were asking how I called my initial variants. For you tool, I did use dng dnm --ped pedFile, --vcf VCFfile. Thanks Reed!

**Comment by dconrad** [comment]
Hi Simonzzc034  - are your 10K trios for the DDD project at the Sanger Institute, or is this something else? There are not too many 10K trio datasets out there, so I was just curious...

**Comment by reedacartwright** [comment]
@simonzzc034, Sorry that I didn't respond earlier. `dng dnm` is designed to work with the output of samtools/bcftools variant calling pipeline. It expects `PL` fields.  We have an open issue #236 for improving `dng dnm` and `dng call` to support additional fields.

**Comment by simonzzc034** [comment]
@dconrad, it is a separate data set but in collaboration with Sanger
Institute DDD,
https://globenewswire.com/news-release/2017/02/01/912907/0/en/OPKO-S-GeneDx-Announces-Research-Collaboration-with-the-Wellcome-Trust-Sanger-Institute.html

**Comment by reedacartwright** [comment]
Closing as possibility fixed.

**Comment by dantaki** [comment]
This is not fixed. The most recent version of dng still fails to call insertions from GATK

**Comment by reedacartwright** [comment]
@dantaki I will need more information to investigate. E.g.

1. What version are you using?
1. What command line are you using?
1. Please provide an example VCF containing lines that fail to be called, including pedigree information, etc.

Remember, if you are using `dng dnm`, it requires PL fields in order to call mutations. `dng call` requires AD fields.

**Comment by dantaki** [comment]
Thanks for the swift reply @reedacartwright. I don't have all the details except for dng version 1.1.1. Someone else will follow up shortly. The VCFs we are using have been processed with GATK and VQSR. They contain both AD and PL entries, since we use those for our analysis too.

**Comment by aojielian** [comment]
@reedacartwright 
Hi, i got this problem yesterday. i use dng version 1.1.1.
here is an example VCF and ped file:
https://www.dropbox.com/sh/i48t4tkp7a9urm1/AACyeWw3TQJim4zdcbsmNjIda?dl=0

this is my command code:
dng dnm auto --vcf /oasis/projects/nsf/ddp195/dantakli/ssc_sv/snv_vcf/11178.vcf.gz --ped /home/a1lian/split_ped/trio_ped/11178_SSC00368.ped --output_vcf /oasis/projects/nsf/ddp195/a1lian/dnm/dng/11178.SSC00368.dng.auto.vcf

**Comment by reedacartwright** [comment]
@aojielian, the sample names in the vcf do not match the pedigree: `SSC00366	SSC00367	SSC00368	SSC00550` vs `11000	SSC02220	SSC02219	SSC02217	2	1`.

**Comment by aojielian** [comment]
@reedacartwright sorry ,i uploaded a wrong ped, i fixed  it
https://www.dropbox.com/s/dtoog0g8oieghsi/11178_SSC00368.ped?dl=0

**Comment by reedacartwright** [comment]
When using the version from the `develop` branch, I get output for 4 sites.

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	SSC00368
chr17	44207550	.	ATCCTCG	A	0	PASS	RD_MOM=27;RD_DAD=39;MQ_MOM=.;MQ_DAD=.;INDELcode=2	NULL_CONFIG(child/mom/dad):PP_NULL:DNM_CONFIG(child/mom/dad):PP_DNM:RD:MQ	RD/RD/RR:0.947984:RD/RR/RR:0.0520157:42:.
chr1	202742656	.	T	TA	0	PASS	RD_MOM=35;RD_DAD=33;MQ_MOM=.;MQ_DAD=.;INDELcode=2	NULL_CONFIG(child/mom/dad):PP_NULL:DNM_CONFIG(child/mom/dad):PP_DNM:RD:MQ	RD/RR/RD:0.661582:RD/RR/RR:0.338418:32:.
chr2	27966383	.	ACTTG	A	0	PASS	RD_MOM=29;RD_DAD=32;MQ_MOM=.;MQ_DAD=.;INDELcode=2	NULL_CONFIG(child/mom/dad):PP_NULL:DNM_CONFIG(child/mom/dad):PP_DNM:RD:MQ	RD/RD/RR:0.946216:RD/RR/RR:0.0537842:33:.
chr2	155738679	.	ACCATG	A	0	PASS	RD_MOM=35;RD_DAD=41;MQ_MOM=.;MQ_DAD=.;INDELcode=2	NULL_CONFIG(child/mom/dad):PP_NULL:DNM_CONFIG(child/mom/dad):PP_DNM:RD:MQ	RD/RD/RR:0.228462:RD/RR/RR:0.771538:39:.
```

Command line was `dng dnm auto --vcf dng.test.vcf --ped 11178_SSC00368.ped -w out.vcf`

**Comment by aojielian** [comment]
@reedacartwright you mean this one?
https://github.com/denovogear/denovogear/archive/develop.tar.gz

Ok, i'll re-install and try it agian
Thanks

**Comment by aojielian** [comment]
@reedacartwright 
[a1lian@comet-ln2 ~]$ dng version
DeNovoGear Version 1.1.1
i just got three of them(all deletions)
i followed these step to install de novo gear:
 tar -xvzf denovogear*.tar.gz
 cd denovogear*/build
 cmake -DBUILD_EXTERNAL_PROJECTS=1 -DCMAKE_BUILD_TYPE=Release  ..
 make -j4

**Comment by reedacartwright** [comment]
If you install from the `develop.tar.gz` the version number might be a bit off since CMake isn't able to pull it from the git information.

If you didn't run `make install`, then `dng version` will access the globally installed one.

If you want to access `dng dnm` directly, you can try this

```
cd denovogear*/build
src/dng-dnm [arguments]
```

**Comment by aojielian** [comment]
@reedacartwright ok, i use this command code, it's worked !
/home/a1lian/denovogear-develop/build/src/dng-dnm auto --vcf dng.test.vcf --ped /home/a1lian/split_ped/trio_ped/11178_SSC00368.ped -w out.vcf

Thank you so much

**Comment by dantaki** [comment]
Thanks for your help @reedacartwright
