### ISSUE TITLE
SegFault in dng dnm

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#250]
From @zhangjianruwang

> I have a problem of core dumped.
I tried many running environment and feel the problem is caused by BCF file format.
the command I use to produce BCF is:
"samtools mpileup -gDf ref.fa father.bam mother.bam brother1.bam brother2.bam sister1.bam > bcffile.bcf"
should I use only 1 offspring?

**Comment by reedacartwright** [comment]
`dng dnm` assumes that it is given a trio. I am not sure how robust it is if given something other than a trio.

If you want to estimate mutations from a large pedigree, you should look at `dng call` in the developed branch. It supports calling mutations using general zero-loop pedigrees.

**Comment by jgarciamesa** [comment]
Hello @zhangjianruwang, I recently was able to fix a "core dumped" error on `dng dnm`. The changes should be merged into our develop branch soon. Please, once they are merged, try to re-run your command with those changes. You should not encounter any problems.

**Comment by zhangjianruwang** [comment]
@reedacartwright    I have tried a trio calling, but also got errors.
@jgarc111   I can find the commits at 20th Feb,2018.  But there is no update in the release page.    how can I apply your changes.

**Comment by jgarciamesa** [comment]
@zhangjianruwang You can find the most recent changes in the develop branch. You can either clone the repository and checkout the develop branch or download our most recent beta version. Instructions for that can be found [here](https://github.com/denovogear/denovogear#installation)

**Comment by zhangjianruwang** [comment]
thank you for your explanation.  I didn't noticed that.
