### ISSUE TITLE
Get rid of old dependencies

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#26]
Migrate `dng dnm` and `dng phaser` to htslib, boost, eigen, etc.

**Comment by kaeldai** [comment]
Update: 
dng-dnm and dng-phaser has been updated to now use htslib 1.2. Code in github.com/kaeldai/denovogear/tree/feature/htslib1.2. Works with the include/dng/hts/ code in develop (as of 06/07/15).

dng-dnm has been tested using SNP mutations for both paired and trio cases (see test/CMakeLists.txt). However dng-phaser and dng-dnm indel mutations has not been tested. Currently I am reverse engineering some more test cases and fixing bugs where I find them.

**Comment by reedacartwright** [comment]
Please send a pull request from that branch.
