### ISSUE TITLE
BCF:   incorrect number of fields (6 != 5) at 927143687:4074044

### ISSUE THREAD

**Issue by zhangjianruwang** [denovogear/denovogear#260]
the command I use to produce BCF is 
samtools mpileup -gDf hg19 female.bam male.bam offspring.bam
       
          the colume title of BCF is 
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  female  male  offspring
 
          the command I use to call denovo mutations is 
dng dnm auto --ped   ped   --bcf  bcf 

          and I got this error in two trios
 incorrect number of fields (6 != 5) at  *****:****

**Comment by zhangjianruwang** [comment]
So what the error is?  how can I solve it?

**Comment by jgarciamesa** [comment]
What version of bfctools are you using? (`bcftools --version`) Also, what version of DeNovoGear are you using?

**Comment by reedacartwright** [comment]
The error occurs when you use a recent version of bcftools with an old
version of dng dnm. Try installing from the develop branch.

--
Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute
Arizona State University
==================
Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign B-220C, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by reedacartwright** [comment]
Marking: Resolved in Develop branch.
