### ISSUE TITLE
Problem during the make step of the installation

### ISSUE THREAD

**Issue by Antoine-Fav** [denovogear/denovogear#262]
Hello,

I am trying to install denovogear on a server but during the "make" step I get these error messages:
```
[  9%] Built target eigen3
[ 18%] Built target boost
[ 19%] Building CXX object src/CMakeFiles/dng-call.dir/lib/call.cc.o
In file included from /mypath/denovogear-1.1.1/src/include/dng/pedigree.h:28,
                 from /mypath/denovogear-1.1.1/src/lib/call.cc:37:
/mypath/denovogear-1.1.1/src/include/dng/matrix.h:59: error: expected constructor, destructor, or type conversion before 'int'
/mypath/denovogear-1.1.1/src/lib/call.cc:356: error: expected '}' at end of input
make[2]: *** [src/CMakeFiles/dng-call.dir/lib/call.cc.o] Error 1
make[1]: *** [src/CMakeFiles/dng-call.dir/all] Error 2
make: *** [all] Error 2
```
We are using Redhat 6, with c++0x compiler. Boost and Eigen were successfully installed.  Any clue on what the problem might be?

By the way, I also tried with docker installation from the link: docker pull quay.io/biocontainers/denovogear with command line: docker pull quay.io/biocontainers/denovogear. Unfortunately I got another error as following:
```
Pulling repository quay.io/biocontainers/denovogear
Tag latest not found in repository quay.io/biocontainers/denovogear
```
-------------------------------------------------
EDIT:
It seems to work with bioconda2

**Comment by Antoine-Fav** [comment]
By the way, I also tried with docker installation from the link: docker pull quay.io/biocontainers/denovogear with command line: docker pull quay.io/biocontainers/denovogear. Unfortunately I got another error as following:
```
Pulling repository quay.io/biocontainers/denovogear
Tag latest not found in repository quay.io/biocontainers/denovogear
```
In advance, thanks a lot for your help.

**Comment by jgarciamesa** [comment]
Hello @Antoine-Fav, please try the develop branch, where you can find our most recent changes.

**Comment by reedacartwright** [comment]
Closing as bioconda fixes it.
