### ISSUE TITLE
dng dnm VCF output : off-by-one?

### ISSUE THREAD

**Issue by MikeHala** [denovogear/denovogear#265]
Hello,

I am using denovogear (1.1.1), samtools (1.6) and bcftools (1.6), ref genome hg38.

The command I used to call the denovos in WGS human trio data  (male proband) was:
time samtools mpileup -t DP -gf ${REF_SEQ} ${DATA_DIR}/${PRO_ID}.chrX.bam ${DATA_DIR}/${DAD_ID}.chrX.bam ${DATA_DIR}/${MOM_ID}.chrX.bam | bcftools norm -m-both | grep -v '<\*>'  | dng dnm XS --ped ${PED_FILE} --bcf - --write ${DATA_DIR}/${PRO_ID}.chrX.DNG.vcf

When I tried to validate the output VCF with GATK ValidateVariants I got the following error message:
##### ERROR MESSAGE: File .../76445.chrX.DNG.vcf fails strict validation: the REF allele is incorrect for the record at position chrX:251475, fasta says TTTG vs. VCF says CTTT 

and similarly for the VCF file for the 22 autosomal chromosomes
##### ERROR MESSAGE: File ....76445.auto.DNG.vcf fails strict validation: the REF allele is incorrect for the record at position chr1:94571, fasta says C vs. VCF says T 

After a quick check for those two with UCSC genome browser I realized that while the REF is correct, the pos is off by 1, i.e. , CTTT is found in chrX:251474  (and similarly for the chr1 variant).

I have decremented all positions in the 2 VCFs by 1 and now the VCFs pass the ValidateVariants test. Am I doing something wrong?

Best,
Mike

**Comment by reedacartwright** [comment]
Can you try the develop branch of DNG to see if it fixes the issue?

Also can you check your pipe and see if the issue occurs before the data is
sent to dng dnm?

**Comment by reedacartwright** [comment]
Assuming that this issue is fixed.

**Comment by MikeHala** [comment]
Sorry for my delayed reply.
I have not tried the dev branch yet, the issue is related to v.1.1.1.
The positions in the standard output format are correct, off-by-one happens when requesting VCF output:
time gunzip -c $VCF_FILE | dng dnm auto --ped ${PED_DIR}/${PRO_ID}.ped --vcf - --write ${OUT_DIR}/${PRO_ID}.denovo.vcf

**Comment by reedacartwright** [comment]
I confirmed that `dng-dnm` creates a vcf output file in which the positions are off by 1.

**Comment by reedacartwright** [comment]
I have committed a fix to the develop branch. If you can get it running, please confirm that it has been fixed for you.
