### ISSUE TITLE
Total number of SNP sites interrogated: 0

### ISSUE THREAD

**Issue by jielab** [denovogear/denovogear#266]
Dear all:

I have a small VCF file (2Mb) for a trio, which I generated by using "bcftools merge *vcf.gz | bcftools convert -Oz -o trio.vcf.gz ". I now put this VCF file at 
https://www.dropbox.com/s/dr19jlu89ai02ev/trio.vcf.gz?dl=0

Then I tried to run it with denovogear, with the command of "dng dnm auto --rd_cutoff 0 --ped sample.ped --bcf trio.vcf.gz".

However, please refer to the log below. Somehow no variants was found by denovogear. Can someone please help me to figure out why this is the case?

DeNovoGear v1.1.1
read depth filter: 0
Created SNP lookup table
 First mrate: 1 last: 1
 First code: 6 last: 6
 First target string: AA/AA/AA last: TT/TT/TT
 First tref: 0.0002388 last: 0.99301
Created indel lookup table First code: 6 last: 6
 First target string: RR/RR/RR last: DD/DD/DD
 First prior: 0.05 last: 0.114
Created paired lookup table
 First target string: AA/AA last: TT/TT
 First prior 1 last: 1
Total number of SNP sites interrogated: 0
Total number of SNP sites passing read-depth filters: 0
Total number of INDEL sites interrogated: 0
Total number of INDEL sites passing read-depth filters: 0
Total number of Paired sample sites interrogated: 0
Total number of Paired sample sites passing read-depth filters: 0
Done !

**Comment by reedacartwright** [comment]
Please post a copy of your ped as well.

**Comment by jielab** [comment]
below is my sample.ped file:

1 18-CG-15-07932_S5_R1_001 0 0 1 0
1 18-CG-15-07931_S4_R1_001 0 0 2 0
1 18-CG-15-07930_S3_R1_001 18-CG-15-07932_S5_R1_001 18-CG-15-07931_S4_R1_001 1 1

**Comment by jielab** [comment]
Yes, I posted. Thanks!

 

jie

**Comment by jielab** [comment]
Can someone please help me out on this?
Thank you very much!
Jie

**Comment by jgarciamesa** [comment]
Please try the develop branch of DNG, were you can find our most recent changes. Running the same command I obtained the following output:

 Created SNP lookup table
 First mrate: 1 last: 1
 First code: 6 last: 6
 First target string: AA/AA/AA last: TT/TT/TT
 First tref: 0.0002388 last: 0.99301

Created indel lookup table First code: 6 last: 6
 First target string: RR/RR/RR last: DD/DD/DD
 First prior: 0.05 last: 0.114

Created paired lookup table
 First target string: AA/AA last: TT/TT
 First prior 1 last: 1

Total number of SNP sites interrogated: 113167
Total number of SNP sites passing read-depth filters: 33289
Total number of INDEL sites interrogated: 15650
Total number of INDEL sites passing read-depth filters: 2413
Total number of Paired sample sites interrogated: 0
Total number of Paired sample sites passing read-depth filters: 0
Done !

**Comment by jielab** [comment]
Do you mean that I download the developing version of DNG and then run the same command?

 

I will try that.

 

Thanks!

 

Jie

**Comment by jielab** [comment]
CMake Error at Modules/ExternalDep.cmake:361 (MESSAGE):
  ERROR: Some dependecies could not be found on your system.  To download and
  build the missing dependecies please set the following configuration
  variable

      BUILD_EXTERNAL_PROJECTS=1

  E.g.  cmake -DBUILD_EXTERNAL_PROJECTS=1 .

**Comment by jgarciamesa** [comment]
You have some missing dependencies. In order to proceed you can either install them yourself or do 
`cmake -DBUILD_EXTERNAL_PROJECTS=1 ..`
instead of just `cmake ..`. That should take care of your missing dependencies.

**Comment by jielab** [comment]
I still can't  believe that the release version that i installed could not do such a simple task that i am trying to do, simply process a trio VCF file with a very small number of SNPs. I just tried to install the beta version with the -DBUILD_EXTERNAL_PROJECTS=1 option, but it failed. Please see below.

  does not match expected value
    expected: '16D78F90B72F29971B042E8DA8BE6843'
      actual: '16d78f90b72f29971b042e8da8be6843'
-- Hash mismatch, removing...
CMake Error at ext_htslib-stamp/download-ext_htslib.cmake:157 (message):
  Each download failed!
make[2]: *** [ext_deps/htslib/src/ext_htslib-stamp/ext_htslib-download] Error 1
make[1]: *** [CMakeFiles/ext_htslib.dir/all] Error 2
make: *** [all] Error 2

**Comment by reedacartwright** [comment]
It looks like the hash needs to be in lowercase. I just committed change 6723027 to the develop branch that should fix that issues.

Please run `git pull` or re-download the develop branch.

**Comment by jielab** [comment]
Dear all:

i now finally installed the development version and got it run. However, please see my log file below. This time it says: Total number of Paired sample sites interrogated: 0. Therefore, there is no output file generated. I did set the read depth filter to 0. Why still so many variants failed read-depth filters?

I am really a bit frustrated with this. I am simply trying to run something that should be very simple to run. 
=======================================

dng dnm auto --rd_cutoff 0 --ped sample.ped --bcf trio.vcf.gz

Created SNP lookup table
 First mrate: 1 last: 1
 First code: 6 last: 6
 First target string: AA/AA/AA last: TT/TT/TT
 First tref: 0.0002388 last: 0.99301

Created indel lookup table First code: 6 last: 6
 First target string: RR/RR/RR last: DD/DD/DD
 First prior: 0.05 last: 0.114

Created paired lookup table
 First target string: AA/AA last: TT/TT
 First prior 1 last: 1

Total number of SNP sites interrogated: 113167
Total number of SNP sites passing read-depth filters: 33289
Total number of INDEL sites interrogated: 15650
Total number of INDEL sites passing read-depth filters: 2413
Total number of Paired sample sites interrogated: 0
Total number of Paired sample sites passing read-depth filters: 0
Done !

**Comment by reedacartwright** [comment]
You are analyzing a trio. You should expect to see no results for the paired-sample analysis.
As to why so many so many sites are being filtered, I'm not sure. Perhaps @gatoravi knows what is going on.

You can also try `dng call` (see documentation in the readme), as I can be more helpful with that program.

**Comment by jielab** [comment]
Dear Reed:

 

Thank you very much! Can you please let me know the exact command that I should use to analyze my trio data?

 

Yes, I will read the documentation and the paper more, after I see something working and get a little bit encouraged to do so.

 

Thank you very much & best regards,

Jie

**Comment by jgarciamesa** [comment]
Hi @jiehuang001, after inspecting your VCF file we realized that although you have 'AD' and 'DP' tags the values for at least the majority of them are missing or zero and our tool needs those values in order to run.

**Comment by jielab** [comment]
Thanks. I will try to use samtools to recreate my VCF file so that "AD" and "DP" values are preserved. Right now, i used bcftools to merge 3 files. I assume that those two tags are messed up since bcftools don't know how to calculate a value from 3 files.

Regarding the comment "You are analyzing a trio. You should expect to see no results for the paired-sample analysis" from Reed,  I think "dng dnm auto" is able to process trio data, as shown in the Github tutorial example. 

Best regards,
Jie

**Comment by reedacartwright** [comment]
I guess you now have it working, so I am closing this issue.
