### ISSUE TITLE
Running DNG in parallel

### ISSUE THREAD

**Issue by aschoenr** [denovogear/denovogear#271]
I was wondering if there was a built in way for DNG to process an entire genome in parallel? I know it is possible to split the genome into chromosomes and then run DNG in parallel on each individual chromosome, but I was wondering if there was a way to do this automatically with DNG.

If not, what tool do you recommend to split the BAM files? I used bamtools split as a test. I then ran DNG on one of the chromosomes and got the following warnings: 

[W::bam_hdr_read] EOF marker is absent. The input is probably truncated

Is this anything to worry about? If not, I can use this tool to split up the BAM files and then write a script to run DNG on each chromosome in parallel. Please let me know if there is a better way to do this as the splitting takes a considerable amount of time to do on my system and I have 60+ trios I need to analyze.

Thanks for your help.

**Comment by reedacartwright** [comment]
Are you running `dng dnm` or `dng call`?

**Comment by aschoenr** [comment]
Sorry, dng dnm.

**Comment by reedacartwright** [comment]
What command are you using to generate your vcfs for `dnm`?

**Comment by aschoenr** [comment]
samtools mpileup -t DP -gf Homo_sapiens_assembly38.fasta [bam1] [bam2] [bam3] | dng dnm auto --ped [pedfile] --bcf

**Comment by reedacartwright** [comment]
If your bam files are indexed, you don't need to split them. Instead, use the `-r` flag to samtools mpileup to restrict the output to specific regions/chromosomes.

Also, if you have multiple trios, you can run `dng dnm` on several trios in parallel.

**Comment by aschoenr** [comment]
Thanks for letting me know. My preprocessing pipeline is setup to process a family's worth of data at a time (4-7 individuals) which produces 2-5 trios to be run. I would prefer to run the entire pipeline (from raw reads to dnm calls) start to finish, so I won't have enough trios ready at a given time to keep my machine busy. For this reason I'd prefer to run DNG in parallel over a trio.

All of that said, I assume I could just use the -r flag on samtools mpileup to run DNG on a specific chromosome, and just run 23 of these calls in parallel. Does that sound reasonable?

**Comment by reedacartwright** [comment]
Yes it does sound reasonable.

I also recommend that since you have family level data that you experiment with `dng call`, which can handle arbitrarily large families. If you use `dng call` you will not have to split the family into trios before processing.

**Comment by aschoenr** [comment]
I will look into both of these. Thanks for your help.

**Comment by aschoenr** [comment]
I've looked into this a little bit and I still have a few questions. First, does dng call give essentially the same information that dng dnm does (ie, for each child it will call the denovo mutations and provide the location?

Second, I am planning on still using samtools mpileup to create a bcf to pass to dng. I assume this is OK? Here is what I'm doing right now:

`samtools mpileup -t DP -r chr1 -gf Homo_sapiens_assembly38.fasta [bam1] [bam2] [bam3] [bam4] [bam5] | dng call --ped [ped file]`

The call to samtools seems to work fine, the one to dng not so much. Do I need to specify a "model" as in the example call? If so, can you please briefly describe what the options mean?

Thanks again for all the help.

**Comment by reedacartwright** [comment]
My response below assumes that you will be working on the latest version of `dng call` from the develop branch because I can't remember what features other versions have.

First, note that the ped file used in `dng call` is different than the ped file used in `dng dnm`. (And the next big change I make to `dng call` will improve its ped-file format further.)

`dng call` works off of `AD` format fields and will estimate the probability that each site has a mutation and if there is a signal of a single mutation, it will output the location (DNL) and type of mutation (DNT). This location can be anywhere in the pedigree, including germline and somatic branches. There is a flag (`--all`) that I introduced recently that will also allow you to call sites with segregating variation as well.

Since `dng call` works off of AD fields, you need to make sure that it is included by `mpileup`. (Note the switch to `bcftools` from `samtools`, because that is what I test against.)

```
bcftools mpileup -a AD -O u -r chr1 -f Homo_sapiens_assembly38.fasta \
    [bam1] [bam2] [bam3] [bam4] [bam5] | dng call --ped [ped file] bcf:-
```

The model parameter defaults to `autosomal` and you do not need to set it unless you want something different. Most of the parameters configure the internal statistical model and you don't need to set them unless you want to optimize the model to your data.  `dng call --help` will provide brief descriptions of parameters. If there is any parameter that you want to know more about, just ask.

`dng call` outputs a vcf, in which every sample column represents a node in the pedigree. Only tip nodes will have PL, DP, and AD set.

Once you get an output from `dng call`, I'll help you understand it.

**Comment by aschoenr** [comment]
Thanks for all of the info. I have a question regarding the newick-formatted trees required in the PED files for dng call. The family I'm currently working on has ID 2014_34. The members are 2014034 (father), 2014035 (mother), 2014036 (son), 2014037 (daughter) and 2014038 (son). Here is the PED file I used for dng dnm:

> 2014_34 2014036 2014034 2014035 1 0
> 2014_34 2014037 2014034 2014035 2 0
> 2014_34 2014038 2014034 2014035 1 0


I'm not sure how to change the last column for dng call.

Also, to clarify, will the output of dng call include all of the information produced by dng dmn in some form (ie. the DNMs and their locations in each of the children)? It's not an issue if the output needs to be further processed, just making sure that dng call will give me the information I'm looking for.

**Comment by reedacartwright** [comment]
Assuming that the column names in your vcf are 2014034--2014038 and you have one column per individual, you can construct your `dng call` pedigree as below. (Note that you need to replace the spaces between values by a tab.)

```
2014_32    2014034    0          0          1    2014034
2014_32    2014035    0          0          2    2014035
2014_34    2014036    2014034    2014035    1    2014036
2014_34    2014037    2014034    2014035    2    2014037
2014_34    2014038    2014034    2014035    1    2014038
```

I haven't compared `dng call` output to `dng dnm` in a long time, but `dng call` will identify de novo mutations and tell you where they are located, what they look like, and provide quality control statistics as well. You will want to look at the DNP, DNL, DNT info tags to start with.

**Comment by aschoenr** [comment]
I tried running that command and got the following error:

> [E::hts_open] fail to open file 'bcf:-'
> unable to open input file 'bcf:-'.

It seems the first command (bcftools mpileup)  worked fine though.

**Comment by reedacartwright** [comment]
This might be a version issue. What does `dng call --version` output?

--
Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute
Arizona State University
==================
Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign B-220C, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by aschoenr** [comment]
dng call v1.1.1-139-gc5b8797
Copyright (c) 2014-2015 Reed A. Cartwright, Kael Dai, et al.

**Comment by reedacartwright** [comment]
Ah, you are using a version from 2016, which means that you are encountering a bug with how pipes were handled. A possible workaround is to write to a bcf file and then read from it, or skip `mpileup` and let `dng call` process the bam files directly.

Or you can upgrade to the latest version on the develop branch which fixes the bug you encountered.

**Comment by reedacartwright** [comment]
@aschoenr, I just committed an improvement to the `develop` branch that makes pedigree parsing more expressive and robust. If you install it, then you will need to use the following for your ped file.

```
##PEDNG v1.0
#Individual Dad Mom Sex Samples
2014034    .          .          1    2014034
2014035    .          .          2    2014035
2014036    2014034    2014035    1    2014036
2014037    2014034    2014035    2    2014037
2014038    2014034    2014035    1    2014038
```

**Comment by aschoenr** [comment]
I could've sworn I was using a recent pull from the development branch...there have been a few people playing with dnm on this machine though. Anyways, I just downloaded the latest from the dev branch and got the following errors when trying to build it:

[aschoenr@bratty build]$ cmake ..
-- Compiling with build type 'RelWithDebInfo'.
-- DeNovoGear version: 1.1.1-308-g3ae70ba.
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   unit_test_framework
-- Found HTSLIB 1.8
CMake Error at src/lib/CMakeLists.txt:38 (target_compile_features):
  target_compile_features The compiler feature "cxx_constexpr" is not known
  to CXX compiler

  "GNU"

  version 4.4.7.


-- Configuring incomplete, errors occurred!
See also "/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeOutput.log".
See also "/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeError.log".
[aschoenr@bratty build]$ vim CMakeFiles/CMakeError.log 
[aschoenr@bratty build]$ sudo cmake ..
[sudo] password for aschoenr: 
sudo: cmake: command not found
[aschoenr@bratty build]$ vim CMakeFiles/CMakeError.log 
[aschoenr@bratty build]$ cmake ..
-- Compiling with build type 'RelWithDebInfo'.
-- DeNovoGear version: 1.1.1-308-g3ae70ba.
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   unit_test_framework
-- Found HTSLIB 1.8
CMake Error at src/lib/CMakeLists.txt:38 (target_compile_features):
  target_compile_features The compiler feature "cxx_constexpr" is not known
  to CXX compiler

  "GNU"

  version 4.4.7.


-- Configuring incomplete, errors occurred!
See also "/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeOutput.log".
See also "/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeError.log".


**And the contents of CMakeError.log is:**


Determining if the pthread_create exist failed with the following output:
Change Dir: /home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_e1117/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_e1117.dir/build.make CMakeFiles/cmTC_e1117.dir/build
gmake[1]: Entering directory `/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e1117.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_e1117.dir/CheckSymbolExists.c.o   -c /home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_e1117
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e1117.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_e1117.dir/CheckSymbolExists.c.o  -o cmTC_e1117
CMakeFiles/cmTC_e1117.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0xc): undefined reference to `pthread_create'
collect2: ld returned 1 exit status
gmake[1]: *** [cmTC_e1117] Error 1
gmake[1]: Leaving directory `/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_e1117/fast] Error 2

File /home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}



I also put this up on pastebin, the formatting here is a bit weird: https://pastebin.com/RgPt1Sm6

**Comment by reedacartwright** [comment]
It looks like your system defaults to using a very old GNU C++ compiler, version 4.4.7. I think that the earliest version of GCC that DeNovoGear will compile against is 4.8.2. If you have access to a more recent compiler installed on your system, the quickest way to compile DeNovoGear is to do the following:

```
mkdir denovogear/build-gcc5
cd denovogear/build-gcc5
CC=gcc5 CXX=g++5 cmake -DBUILD_EXTERNAL_PROJECTS=force ..
make
```

This assumes that the compilers you want to use are `gcc5` and `g++5`. You may run into linking issues if you link against a boost library compiled with GCC 4.4.7.  I use `-DBUILD_EXTERNAL_PROJECTS=force` to ensure that when you run make, dependencies are downloaded and compiled using the same compiler as denovogear.

If you don't have access to a recent version of GCC, the alternative is to install denovogear via bioconda. We have a pull request (https://github.com/bioconda/bioconda-recipes/pull/8309) in right now to bioconda to update their DeNovoGear packages. Once it is accepted, you should be able to install a recent version of DeNovoGear using bioconda.

**Comment by aschoenr** [comment]
I forgot that I had gcc7 installed, just not enabled. Should what I did below work, or should I be doing something else? It seems that even though I have gcc7 enabled, it is still defaulting to gcc 4.

[aschoenr@bratty build]$ scl enable devtoolset-7 bash
[aschoenr@bratty build]$ which gcc
/opt/rh/devtoolset-7/root/usr/bin/gcc
[aschoenr@bratty build]$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.2.1-20170829/obj-x86_64-redhat-linux/isl-install --enable-libmpx --with-mpc=/builddir/build/BUILD/gcc-7.2.1-20170829/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.2.1 20170829 (Red Hat 7.2.1-1) (GCC) 
[aschoenr@bratty build]$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.2.1-20170829/obj-x86_64-redhat-linux/isl-install --enable-libmpx --with-mpc=/builddir/build/BUILD/gcc-7.2.1-20170829/obj-x86_64-redhat-linux/mpc-install --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.2.1 20170829 (Red Hat 7.2.1-1) (GCC) 
[aschoenr@bratty build]$ cmake ..
-- Compiling with build type 'RelWithDebInfo'.
-- DeNovoGear version: 1.1.1-308-g3ae70ba.
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   unit_test_framework
-- Found HTSLIB 1.8
CMake Error at src/lib/CMakeLists.txt:38 (target_compile_features):
  target_compile_features The compiler feature "cxx_constexpr" is not known
  to CXX compiler

  "GNU"

  version 4.4.7.


-- Configuring incomplete, errors occurred!
See also "/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeOutput.log".
See also "/home/aschoenr/work/apps/denovogear/build/CMakeFiles/CMakeError.log".

**Comment by aschoenr** [comment]
I did this instead:

[aschoenr@bratty denovogear]$ mkdir build-gcc7
[aschoenr@bratty denovogear]$ cd build-gcc7/
[aschoenr@bratty build-gcc7]$ CC=/opt/rh/devtoolset-7/root/usr/bin/gcc CXX=/opt/rh/devtoolset-7/root/usr/bin/g++ cmake -DBUILD_EXTERNAL_PROJECTS=force ..

compiling now, I'll let you know when I hit my next snag.

**Comment by aschoenr** [comment]
Seems to be running fine now. I am still running it onlt on chr1. Is there somewhere I can go for a description of the output or can you help me with that? Here is an example entry from the output:

chr1    867096  .   T   A   5.76188 PASS    MUTQ=5.68276;MUTX=0.729776;LLD=-25.5525;LLS=-12.5282;LLH=-8.16552;DENOVO;DNP=0.729776;DNQ=99;DNT=T/T*T/T->T/A;DNL=LB/2014038;GERMLINE;SOMATIC;LIBRARY;DP=129;AD=121,8   GT:GQ:GP:MUTP:DNP:PL:DP:AD  0/0:23:0.995202,0.00479806,0:0:0:.,.,.:.:.,.    0/0:41:0.99992,8.01982e-05,0:0:0:.,.,.:.:.,.    0/0:23:0.995202,0.00479806,0:0:0:0,60,490:20:20,0   0/0:41:0.99992,8.01982e-05,0:0:0:0,78,607:26:26,0   0/0:66:1,2.57071e-07,0:1.70721e-11:1.68082e-11:0,43,569:27:26,1 0/0:55:0.999997,3.27796e-06,0:2.13075e-11:1.79451e-11:0,32,648:34:32,2  0/1:6:0.265346,0.734654,0:1:1:87,0,363:22:17,5

**Comment by reedacartwright** [comment]
It's great you got it compiled and working.

`dng call` outputs a VCF format file. If you are not familiar with the format, see https://gatkforums.broadinstitute.org/gatk/discussion/1268/what-is-a-vcf-and-how-should-i-interpret-it about how to interpret it.

The VCF header contains descriptions of all of the statistics that `dng call` outputs. The `DN*` family of statistics is probably the one you want to focus on intially. (The other statistics are useful for filtering once you get to that step).
 * DNP: Estimated probability that the site has exactly 1 mutation, in this case 72.9%.
 * DNT: Predicted mutation pattern, in this case two T/T homozygotes produced a T/A child.
 * DNL: Predicted location of a mutation, in this case 2014038.
 * DNQ: Join quality of DNT and DNL, [phred-scaled](https://en.wikipedia.org/wiki/Phred_quality_score) and assuming that there is one mutation. In this case if there is one mutation, then DNL and DNT have a 1e-10 change of being wrong.

**Comment by reedacartwright** [comment]
@aschoenr How is it going? Do you have any more questions?

**Comment by aschoenr** [comment]
Thanks for getting in touch again. I am actually having a bit of difficulty. I've gone back to using the dnm module, but for some reason I cannot get it to run, I keep getting the following error:

```
Unable to find trio. Code 1:3 
 BCF PARSING ERROR - Trios!  -3
 Exiting !
```


Here is what I'm trying to do:

`samtools mpileup -t DP -r chr1 -gf Homo_sapiens_assembly38.fasta 2003058.bam 2003057.bam 2003003.bam  | dng dnm auto --ped 2003_57.ped --bcf -`

Here is my ped file (I tried both space and tab delimited):

```
2003_57	2003058	2003057	2003003	2	0
2003_57	2003059	2003057	2003003	2	0
2003_57	2003060	2003057	2003003	2	0
```


I saw in another thread that it may be a mismatch between my bcf file and my ped file. I looked at the SM records in the bam files I'm inputting to samtools and they seem to be fine:

```
samtools view -H 2003058.bam | grep SM
@RG	ID:HJVWWCCXX	SM:2003058	LB:WAKE_2003058	PL:ILLUMINA	PU:HJVWWCCXX.NGCTCATT	CN:BI	DT:2018-05-17T05:19:07-0400

samtools view -H 2003057 | grep SM
@RG	ID:HJVWWCCXX	SM:2003057	LB:WAKE_2003057	PL:ILLUMINA	PU:HJVWWCCXX.NCCGGAGA	CN:BI	DT:2018-05-17T05:19:07-0400

samtools view -H 2003003.bam | grep SM
@RG	ID:HJK2YCCXX	SM:2003003	LB:WAKE_2003003	PL:ILLUMINA	PU:HJK2YCCXX.NCTCGCGC	CN:BI	DT:2018-05-17T05:19:07-0400
```

Any ideas?

**Comment by reedacartwright** [comment]
Which version of `dng-dnm` is throwing that error? I've looked for that error message in the develop branch and can't find it.

**Comment by aschoenr** [comment]
Looks like I was using the wrong version (again). I tried again with the following version:

```
dng dnm v1.1.1-308-g3ae70ba
Copyright (c) 2014-2018
```

and got comparable errors. Here are a few:

```
 BCF PARSING ERROR - Unable to find trio!
 Members missing: 1!
 Skipping site10000


 BCF PARSING ERROR - Unable to find trio!
 Members missing: 1!
 Skipping site10000


 BCF PARSING ERROR - Unable to find trio!
 Members missing: 1!
 Skipping site10001


 BCF PARSING ERROR - Unable to find trio!
 Members missing: 1!
 Skipping site10001


 BCF PARSING ERROR - Unable to find trio!
 Members missing: 1!
 Skipping site10002


 BCF PARSING ERROR - Unable to find trio!
 Members missing: 1!
 Skipping site10002


 BCF PARSING ERROR - Unable to find trio!
 Members missing: 1!
 Skipping site10003
```

**Comment by reedacartwright** [comment]
It looks like the sample names are not matching up. Can you give me the `#CHROM` header line in the output of `samtools mpileup`?

**Comment by aschoenr** [comment]
I'm going to run samtools mpileup overnight and I'll let you know tomorrow.

**Comment by reedacartwright** [comment]
If you don't want to run the job overnight, you can do the following:

`samtools mpileup -t DP -r chr1 -gf Homo_sapiens_assembly38.fasta 2003058.bam 2003057.bam 2003003.bam | bcftools view -h | tee header.txt`

**Comment by aschoenr** [comment]
I was leaving the office and thought it might be handy to have this bcf file on hand to figure out what's going on. Here is the line you were asking for:

`#CHROM  POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  2003058 2003057 2003003`

I just tried running DNG on that bcf file and got the same errors as before:

`dng dnm auto --ped 2003_57.ped --bcf 2003_58_57_03_chr1.bcf`

Do the mother (2003003) and father (2003057) need individual lines in the ped file? Here is what it currently looks like (currently tab-delimited):

```
2003_57	2003058	2003057	2003003	2	0
2003_57	2003059	2003057	2003003	2	0
2003_57	2003060	2003057	2003003	2	0
```

**Comment by reedacartwright** [comment]
I think `dng-dnm` is trying to call de novos in all three trios that you have in your ped file, and is throwing an error because your input file only contains a single trio. Try either adding both 2003059 and 2003060 to your mpileup output or using a ped file with just the line for 2003058 in it.

**Comment by aschoenr** [comment]
Looks like you are right. I was under the impression that `dng dnm` could only process a single trio at a time. This is nice because I can now process an entire family at a time and parallelize it by processing each chromosome on its own.

Out of curiosity, does the format of the output of `dng dnm` have a formalized name? Also, can you tell me if a few of these records look like they make sense? The last few columns (root mean square of the mapping qualities) have me a bit worried, does it make sense to have a negative number here?

> DENOVO-SNP CHILD_ID: 2003058 chr: chr1 pos: 30885 ref: T alt: C,<*> maxlike_null: 7.88776e-05 pp_null: 0.999874 tgt_null(child/mom/dad): TT/TT/TT snpcode: 1 code: 6 maxlike_dnm: 9.9301e-09 pp_dnm: 0.000125875 tgt_dnm(child/mom/dad): CT/TT/TT lookup: 4 flag: 1 READ_DEPTH child: 29 dad: 37 mom: 18 MAPPING_QUALITY child: -2147483648 dad: -2147483648 mom: -2147483648

> DENOVO-SNP CHILD_ID: 2003059 chr: chr1 pos: 39261 ref: T alt: C,<*> maxlike_null: 6.32285e-10 pp_null: 0.998985 tgt_null(child/mom/dad): CT/CC/TT snpcode: 2 code: 9 maxlike_dnm: 7.96e-13 pp_dnm: 0.00101492 tgt_dnm(child/mom/dad): TT/CC/TT lookup: 4 flag: 1 READ_DEPTH child: 39 dad: 41 mom: 60 MAPPING_QUALITY child: -2147483648 dad: -2147483648 mom: -2147483648

> DENOVO-SNP CHILD_ID: 2003060 chr: chr1 pos: 47960 ref: T alt: A,G,<*> maxlike_null: 3.78472e-05 pp_null: 0.999864 tgt_null(child/mom/dad): AT/TT/AT snpcode: 2 code: 9 maxlike_dnm: 6.26547e-09 pp_dnm: 0.000136156 tgt_dnm(child/mom/dad): AT/TT/TT lookup: 5 flag: 1 READ_DEPTH child: 33 dad: 31 mom: 30 MAPPING_QUALITY child: -2147483648 dad: -2147483648 mom: -2147483648

**Comment by reedacartwright** [comment]
I think that the vcf output of `dng dnm` can only handle one trio at a time. The original output is more flexible.

Unfortunately, I cannot help you with the interpretation of the original output as it was developed before I started contributing to `dng` and I haven't used it in any of my research. @dconrad and @gatoravi might be able to help you understand it.
