### ISSUE TITLE
vcf output in the latest development version

### ISSUE THREAD

**Issue by vsvinti** [denovogear/denovogear#283]
Hi there

I downloaded the development version 12 July 2018. I'm running dng on trios, and it works fine if I do:
<pre> dng dnm auto --ped trio.ped --bcf trio.bcf > trio.autodng.txt </pre>
but if I try to write a vcf file:
<pre> dng dnm auto --ped trio.ped --bcf trio.bcf --write trio.autodng.vcf </pre>
It still outputs the non-vcf format to the screen / log file, and the vcf file is empty. Is writing to vcf still an issue? Is there a quicker way of converting output to vcf once dng has been run?

**Comment by reedacartwright** [comment]
I can't replicate your issue. It is working for me.

**Comment by vsvinti** [comment]
Ok. Have I got the right command? Is the vcf output dependent on a particular version of any dependent software? Is the vcf being written during runtime or just at the end (ie should I expect to see a change in file size before job completes)?

**Comment by vsvinti** [comment]
Does this have anything to do with the fact that all the variants have  <*>, for example  
<pre>pos: 17086870 ref: T alt: C,<*> maxlike_null: 6.26547e-07 </pre>
and maybe the vcf doesn't support them? What are these?

**Comment by reedacartwright** [comment]
I believe that the output file is buffered, so you might not see any information in it before several lines have been written or the program has finished. I recommend trying it on a small input vcf to see if you get what you are looking for.

The '<*>' variants refer to "everything else", as in alleles that were not genotyped but may be there biologically. They are used by mpileup to pass information to bcftools call. I believe that dng dnm understands them as well.

**Comment by vsvinti** [comment]
Ah, you are right! The vcf only gets filled upon job completion. The regular dng output gets printed to the screen during runtime when using --write, which is deceiving..
