### ISSUE TITLE
why the same genetic data could go both ways

### ISSUE THREAD

**Issue by jielab** [denovogear/denovogear#284]
Hi, I am able to finally make DNG work on the example data. Once I run dng dnm auto --ped sample_CEU.ped --bcf sample_CEU.vcf, the output shows a total of 3 variants are de novo. Please see the screenshot below, the proband and the 3 variants highlighted in red.

My question is, the other variant not highlighted in red has the same genetic data as the last variant, except that the REF/ALT is different. Why this variant is not deeded de novo by DNG?

Best regards,
Jie

![capture](https://user-images.githubusercontent.com/26947455/43035033-da0f28bc-8cb5-11e8-8998-7c0bb0656795.JPG)

**Comment by reedacartwright** [comment]
Row 4 is a duplicate for row 3 and is probably being ignored by dng-dnm.

mpileup does unexpected things around indels, sometimes producing duplicated sites.
