### ISSUE TITLE
vcf input but prompted me bcf parsing error

### ISSUE THREAD

**Issue by silvermoon8902** [denovogear/denovogear#296]
Hi,

I am using denovogear to do dnm calling. My command is as follow:

dng dnm auto --ped 35-02451_trio1.ped --vcf 35-02451_trio1_filtered_v1.vcf --output_vcf 35-02451_trio1_filtered_v1_dngout.vcf

Attached please find my .vcf and .ped files.

My command prompted me such error info:
DeNovoGear v1.1.1

output vcf file: 35-02451_trio1_filtered_v1_dngout.vcf
Created SNP lookup table
 First mrate: 1 last: 1
 First code: 6 last: 6
 First target string: AA/AA/AA last: TT/TT/TT
 First tref: 0.0002388 last: 0.99301

Created indel lookup table First code: 6 last: 6
 First target string: RR/RR/RR last: DD/DD/DD
 First prior: 0.05 last: 0.114

Created paired lookup table
 First target string: AA/AA last: TT/TT
 First prior 1 last: 1

 BCF PARSING ERROR - Trios!  -6
 Exiting !

But I didn't provide .bcf file as input. How's this happened?

[dng_input.zip](https://github.com/denovogear/denovogear/files/2785491/dng_input.zip)

**Comment by reedacartwright** [comment]
Please try the develop branch and let us know if the error message still occurs.

**Comment by silvermoon8902** [comment]
But what's the flag for output vcf file in denovogear develop version? --output_vcf is not usable in the develop version. I checked its usage but didn't find the option:
Usage:
Autosomes:
        dng dnm auto --bcf bcf_f --ped ped_f [OR] dng dnm auto --vcf vcf_f --ped ped_f
X chromosome in male offspring:
        dng dnm XS --bcf bcf_f --ped ped_f [OR] dng dnm XS --vcf vcf_f --ped ped_f
X chromosome in female offspring:
        dng dnm XD --bcf bcf_f --ped ped_f [OR] dng dnm XD --vcf vcf_f --ped ped_f

Allowed Options:
  -p [ --ped ] arg                   Ped file to describe relationship between
                                     the samples
  -b [ --bcf ] arg                   BCF file, contains per-sample read depths
                                     and genotype likelihoods
  -v [ --vcf ] arg                   VCF file, contains per-sample read depths
                                     and genotype likelihoods
  -s [ --snp_mrate ] arg (=1e-8)     Mutation rate prior for SNPs
  -i [ --indel_mrate ] arg (=1e-9)   Mutation rate prior for INDELs
  -P [ --pair_mrate ] arg (=1e-9)    Mutation rate prior for paired sample
                                     analysis
  -i [ --indel_mu_scale ] arg (=1.0) Scaling factor for indel mutation rate
  -c [ --pp_cutoff ] arg (=0.0001)   Posterior probability threshold
  -R [ --rd_cutoff ] arg (=10)       Read depth filter, sites where either one
                                     of the sample have read depth less than
                                     this threshold are filtered out
  -r [ --region ] arg                Region of the BCF file to perform denovo
                                     calling. [string of the form
                                     "chr:start-end"
  -o [ --poly_rate ] arg (=1e-3)     Polymorphsim rate - used in prior
                                     calculations
  -m [ --mu_scale ] arg (=1.0)       Scaling factor for indel priors
  -w [ --write ] arg                 Write output to vcf file.
  --version                          display version information
  --help                             display usage informaiton
  --arg-file arg                     read command-line arguments from a file

**Comment by reedacartwright** [comment]
It's towards the bottom.
```
-w [ --write ] arg Write output to vcf file.
```

**Comment by silvermoon8902** [comment]
reedacartwright, thanks so much for your help and I got my first dng result!!

But I am confused how to explain the result. Because it seems not all of the PP_DNM are high in the output file. The truth is most of the PP_DNM are close to 0. Should I still contain this portion of SNPs whose PP_DNM are close to 0 as DNM? Or I should consider those SNPs with PP_DNM more than 0.5 as DNM (because PP_DNM is greater than PP_NULL in such case)?

Attached please find my result vcf file.

[fam35_02451_trio1_dngout.zip](https://github.com/denovogear/denovogear/files/2798288/fam35_02451_trio1_dngout.zip)

**Comment by reedacartwright** [comment]
I unfortunately can't provide many tips on converting the output of `dng dnm` into biological insight. I don't have experience working directly with the statistics outputted by `dng dnm`. My experience in analyzing mutations has been with the output of `dng call`.

**Comment by reedacartwright** [comment]
Closing because your error message is fixed in the develop branch.
