### ISSUE TITLE
dng phaser for indels

### ISSUE THREAD

**Issue by sjin09** [denovogear/denovogear#298]
To whom it may concern,

I am writing to inquire whether "dng phaser --dnm dnm_f --pgt gts_file --bam alignment.bam --window 1000" can also be used to haplotype phase indels and somatic mutations. I have identified germline indels and somatic indels using gatk and strelka2. I would like to be able to use read-backed phasing to haplotype phase these indels, but the example (sample_phasing_dnm_f and sample_phasing_GTs_f) seems to only include SNP for haplotype phasing.

Many thanks,
Sangjin Lee

**Comment by reedacartwright** [comment]
I recommend using whatshap (https://whatshap.readthedocs.io/en/latest/) for read-backed phasing.
