### ISSUE TITLE
[E::bcf_hdr_add_sample] Duplicated sample name '.' Aborted (core dumped)

### ISSUE THREAD

**Issue by Saranya-Balachandran** [denovogear/denovogear#302]
Hi,
On running dng dnm auto --vcf vcf_f --ped ped_f -w out.vcf,
I get [E::bcf_hdr_add_sample] Duplicated sample name '.' Aborted (core dumped)
On querying the sample names using bcftools I get three distinct sample names.
The bcf file has DP, PL record for each sample individually.

Kindly help in understanding this issue.
I'm runing in the denovogear developer mode

Regards,
Saranya

**Comment by Saranya-Balachandran** [comment]
On running on the test data generated by make test in human_trio receiving the same error
dng dnm auto --ped human_trio/ped/trio.ped --vcf human_trio/bcftools/trio.call.vcf

**Comment by reedacartwright** [comment]
The sample data you used is for dng call so the error is expected.

It appears you are using the wrong pedigree format for dng dnm. Can you
update to the format sorted by dng dnm?

**Comment by Saranya-Balachandran** [comment]
Please find below my ped format
##PEDNG v1.0
#ID Dad Mom Sex Samples
SID93046	.	.	2 =
SID93044	.	.	1 =
SID93041	SID93044	SID93046	1 =

**Comment by reedacartwright** [comment]
That's the format recognized by dng-call.  To use dng-dnm follow the
instructions here:

https://github.com/ultimatesource/denovogear/blob/develop/README.md#about-sampleped

**Comment by Saranya-Balachandran** [comment]
Thank you!
