### ISSUE TITLE
Jenkins/Travis Support

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#31]
Get Jenkins or Travis working (again).

**Comment by kaeldai** [comment]
I have a working travis yml file at https://github.com/kaeldai/denovogear/blob/testing/.travis.yml, builds and tests denovogear. However it takes 30 mins to complete, and VM caching may not be possible.

**Comment by stevenhwu** [comment]
Try merge/modify from this one. I got boost/eigen3/bamtools to cache properly. It should work for htslib as well.
https://github.com/stevenhwu/accuMUlate/blob/EM_develop/.travis.yml
https://github.com/stevenhwu/accuMUlate/blob/EM_develop/travis_rebuild_cache.sh

Too much work to merge everything in one file with yml syntax, so the testing caching part is in travis_rebuild_cache.sh

**Comment by reedacartwright** [comment]
@kaeldai Is this closable?

**Comment by kaeldai** [comment]
Yes, we have the core jenkins system set up. We may want to open another ticket for setting up build nodes for Linux and Mac.
