### ISSUE TITLE
bam file for dng-phaser

### ISSUE THREAD

**Issue by mariliascliar** [denovogear/denovogear#311]
Hi, I´m trying to run dng-phaser but it seems it is not reading the bam file at all. When I include the --bam flag, dng-phaser return the result below. Independent if I specify the pathway for bam file or not, the result is the same. When I don´t include the --bam flag, it return an error "INPUT ERROR! Please specify the list of DNMs, list of Parental GTs and the BAM file!"

Do you have any suggestion to resolve this issue?
Thank you!

> > dng-phaser --dnm dnm_file.txt --pgt ind1.PGT.txt --bam ind1.bam --window 300
> > DeNovoGear v1.1.1-unknown --- SNV Phaser
> > 
> > List of DNMs: dnm_file.txt, List of parental GTs: ind1.PGT.txt
> > 
> > DNM_pos chr1:32091818   INHERITED C     VARIANT T - Insufficient reads present to phase this site.
> > DNM_pos chr12:52772135  INHERITED G     VARIANT A - Insufficient reads present to phase this site.
> > The number of lines read DNM file is 2
> 
> _

**Comment by reedacartwright** [comment]
dng-phaser is not supported any more. I recommend that you try whatshap https://whatshap.readthedocs.io/en/latest/guide.html instead of phaser.
