### ISSUE TITLE
No outputs

### ISSUE THREAD

**Issue by Lin-Yuying** [denovogear/denovogear#314]
Hi there,

I encountered an issue recently when using dng-call function in DenovoGear v1.1.1 with command line
`dng-call -f /home/ref/ref.fa -q 30 -Q 30 --ped FR24.ped P271.mark_duplicates.bam P433.mark_duplicates.bam P444.mark_duplicates.bam ...P452.mark_duplicates.bam -o test.vcf` and also tried `dng-call -f /home/ref/ref.fa -q 30 -Q 30 --ped family.ped -s family.samfiles -o test.vcf` . However, there are no output in vcf files in all my analysis, except the header. 

My family ped files looks like this: 
```
##PEDNG v1.0
#individual Father Mother Sex Samples
P271 .    .    male =
P433 .    .    female =
P444 P271 P433 male =
P445 P271 P433 male =
P455 P271 P433 male =
P456 P271 P433 male =
P461 P271 P433 male =
P436 P271 P433 female =
P437 P271 P433 female =
P438 P271 P433 female =
P450 P271 P433 female =
P452 P271 P433 female =
```
The header in vcf files look like this
```
##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##denovogearVersion=1.1.1
##denovogearCommand=dng call
##denovogearArgument=fasta=ref.fa
##denovogearArgument=min-qlen=0
##denovogearArgument=min-prob=0.100000
##denovogearArgument=mu=0.000000
##denovogearArgument=mu-somatic=0.000000
##denovogearArgument=mu-library=0.000000
##denovogearArgument=nuc-freqs=0.3,0.2,0.2,0.3
##denovogearArgument=ped=FR24.ped
##denovogearArgument=min-basequal=30
##denovogearArgument=min-mapqual=30
##denovogearArgument=region=
##denovogearArgument=ref-weight=1.000000
##denovogearArgument=sam-files=
##denovogearArgument=theta=0.001000
##denovogearArgument=output=test.vcf
##fileDate=2021-10-06T10:03:27-0700
##INFO=<ID=LL,Number=1,Type=Float,Description="Log likelihood">
##INFO=<ID=PMUT,Number=1,Type=Float,Description="Probability of mutation">
```

Could you help with this?  Thanks in advance.

**Comment by reedacartwright** [comment]
Can you check to see if this issues persists with the `develop` branch?

**Comment by Lin-Yuying** [comment]
Hi Reed, 

Thanks for your reply. I actually used the Mac version of DenovoGear, and cannot find any branch in the directory. Could you please provide more details of this kind of error? 
Thanks! 

Lin

**Comment by reedacartwright** [comment]
The source code for the develop branch can be downloaded from here: https://github.com/ultimatesource/denovogear/archive/refs/heads/develop.zip

I suspect that if you aren't getting any out that your read group information in your bam files do not match the information in your pedigree file.

**Comment by Lin-Yuying** [comment]
Hi there, 

I solved this issue by replacing '=' with samples names in family ped files.
