### ISSUE TITLE
Support Bed and GFF Formats

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#44]

**Comment by kaeldai** [comment]
@reedacartwright, just to clarify, are you looking to modify the "--region" option to handle bed/gff files as well as literals?

**Comment by reedacartwright** [comment]
Samtools uses regions to create iterators and then uses bed/gff files to exclude/include sites from the regions.  We can do this, or we could focus just on the region format and provide a way to generate regions from bed/gff/vcf format.  We can down the road think of ways to optimize the reading of files if we have complex regions.

**Comment by kaeldai** [comment]
For parsing VCF files by regions, synced_bcf_reader.h has functions for parsing either string-literals or BED files. dng-dnm.cc has code using synced_bcf_reader.h (although a bit more is needed to read in BED regions) which could be added in vcfpileup.h.
