### ISSUE TITLE
Override existing read groups in dng call

### ISSUE THREAD

**Issue by mattjmeier** [denovogear/denovogear#51]
Because BAM files produced by different sources will have different ways of writing the RG tags, it would be very useful to have the ability to override existing read groups in the BAM file.

**Comment by kaeldai** [comment]
I've added a feature to specify what RG tag used to identify libraries by use of "--libtag" option and ran some tests on it. Currently over in my repository at https://github.com/kaeldai/denovogear/tree/feature/read_groups.

However, found an issue with the astyle command on Ubuntu. I want to get it working before I do a pull-request.

**Comment by reedacartwright** [comment]
Partially solved by 4048532

**Comment by reedacartwright** [comment]
Completely solved by ed60c813bc
