### ISSUE TITLE
dnm probabilities maybe too low

### ISSUE THREAD

**Issue by kaeldai** [denovogear/denovogear#56]
AT/AA/AA
child: 0/1:69,62:131:99:1667,0,1866
father: 0/0:229,0:229:99:0,617,7421
mother: 0/0:168,0:168:99:0,427,5249
population heterozygosity of .001

dng-dnm is calculating a posterior of 0.170505, but another script is indicating the true value is 1.0. Use the attached R script and compare transition matrices with that from dnm.

**Comment by kaeldai** [comment]
bcf2Qcall.cc::bcf_2qcall(). dnm assumes there is a "X" in the ALT field, otherwise k1 will be negative and will do an out-of-bound lookup on pl_fields. 

If the PL is not specified explicit then assign to a high (near zero) phred value.

**Comment by reedacartwright** [comment]
Fixed in develop branch.
