### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by rachelss** [denovogear/denovogear#69]
On a Mac:

Ran dng dnm auto --ped examples/sample_paired.ped --bcf examples/sample_CEU.bcf as instructed in the readme (modified for available files in examples folder). Got

Created SNP lookup table
 First mrate: 1 last: 0
 First code: 9 last: 1
 First target string: AA/AA/AA last: TT/TT/TT
 First tref: 9.66184e-09 last: 2

Created indel lookup table First code: 9 last: 0
 First target string: RR/RR/RR last: DD/DD/DD
 First prior: 0.228 last: 2

Created paired lookup table
 First target string: AA/AA last: TT/TT
 First prior 1 last: 1
[vcf.c:759 bcf_hdr_read] invalid BCF2 magic string: only BCFv2.2 is supported.
/usr/local/bin/dng: line 43:  9053 Segmentation fault: 11  $cmdpath $@

**Comment by kaeldai** [comment]
Yes, the README and the example data has been outdated for some time. [Here](https://github.com/kaeldai/denovogear/tree/feature/cleanup) is a new repository with more up-to-date instructions and a better explanation of dng-call (and removes some old unused code).

Reed and Stephen. If you could, read over the description I made of call and let me know what I could change. The descriptions for dnm and phaser I left alone - but changed the examples. I will then do a merge and pull request.

**Comment by reedacartwright** [comment]
Fixed in develop branch.
