### ISSUE TITLE
Test code directure structures (test/src/**)

### ISSUE THREAD

**Issue by stevenhwu** [denovogear/denovogear#86]
I really don't like the current way stevenhwu setup the test dir.
There should be several layers and organized properly
- Shared/header at top level:
  - Shared between all tests, such as boost_check_matrix, rng...etc. **update:** Currently, these are placed at `test/src/boost_test_helper.h`
- Shared/header at local level:
  - See **fixture** ~~Shared between similar test classes, e.g. fixture shared between test2_peeling and testt_time_peeling. One is testing the function, one comparing the performance.~~
  - What/Any prefix for time/performance test? Currently using testt?
-  Actual test files:
  - Do we want to separate testing header/include (*.h) and testing lib (*.cc). Testing lib requires to include a few additional *.cc to CMake.
- CMake
  - Currently `make test` builds everything. Maybe create something like `make timetrial` and/or `make performance` for other codes that will take a while to run. Some of these, if not all should no in the release branch.
  - **update** should be able to add new target in cmake e.g. make timetrial
- Fixture
  - Fixture are used to setup/tear down boost tests. Some fixtures are used in multiple tests, and these are placed in test/src/fixture/*

**Comment by reedacartwright** [comment]
#133 Changed how we are doing tests.

There is now a `Tests` directory which supports both Unit testing and Process testing.  A couple CMake helper functions have been created to support the creation of tests using a common format.

Unit tests are now placed in a directory structure based on CXX namespaces, with the idea that unit tests should be namespace based and not file based.
