### ISSUE TITLE
No insertions reported in 1.1.1

### ISSUE THREAD

**Issue by woodoo46** [denovogear/denovogear#89]
Hi, there,

We have compared the results from 0.5.4 and 1.1.1. We found that in 1.1.1, quite a few of indels were removed from 0.5.4 results. Specifically, there is no insertions reported in 1.1.1. 

Any thought on this?

Thanks.

George

**Comment by reedacartwright** [comment]
What is the command line you are using?

**Comment by woodoo46** [comment]
dng dnm auto --bcf  /dev/stdin --ped ped.txt --outvcf_vcf out.vcf .

I am piping the bcf file to the program. I am now testing using --indel_mrate 0.000000001. I saw in the source code the default value of indel_mrate was set to 0.

**Comment by reedacartwright** [comment]
Okay, let me know what happens.

**Comment by woodoo46** [comment]
Still there is no insertion.  The output from the program confirms that the rate is set.
indel mutation rate: 1e-09

Thanks.

**Comment by reedacartwright** [comment]
@kaeldai Can you look at this?

**Comment by woodoo46** [comment]
Any update on this?

**Comment by kaeldai** [comment]
Yes, should be fixed in pull request #101. Closing.

**Comment by woodoo46** [comment]
So I just recheck out the code, and compile it?

**Comment by reedacartwright** [comment]
Yes, it's on the develop branch and will be in the next release.

**Comment by woodoo46** [comment]
When will you push out new release?

**Comment by reedacartwright** [comment]
I don't know.  Hopefully soon.  Are you having problems compiling from
develop?

**Comment by woodoo46** [comment]
I would like ask my admin to install it; so it is better to have something formal (sort of).

BTW, it is not clear how you guys change the algorithm on calling variants on X. There were thousands of calls on X for a male child. Can you explain a little bit? Or you can point me some documentation to read.

Thanks.
