### ISSUE TITLE
PythonLibs is not found

### ISSUE THREAD

**Issue by reedacartwright** [denovogear/denovogear#91]
If a machine does not have the python development headers and libraries installed it will toss the following error message.

```
CMake Error at /nfs/apps/cmake/3.2.2/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):

  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "2.7")

Call Stack (most recent call first):

  /nfs/apps/cmake/3.2.2/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)

  /nfs/apps/cmake/3.2.2/share/cmake-3.2/Modules/FindPythonLibs.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)

  src/CMakeLists.txt:74 (find_package)

-- Configuring incomplete, errors occurred!
```

Is PythonLibs needed?  If so we need to add documentation about it or work around this error.

**Comment by anderspitman** [comment]
Note for the future: once the newer version of treecall that no longer depends on editdist is integrated, this dependency will also go away.

**Comment by jgarciamesa** [comment]
As of my understanding, PythonLibs requirement was removed in #254
