### ISSUE TITLE
<X> support in call

### ISSUE THREAD

**Issue by kaeldai** [denovogear/denovogear#93]
DNG Call needs to be able to fully support VCF input files with <X> in the alternative alleles field, found in old bcftools output in place of the N. 
- [ ] Create dng-call test case that has both <X> and N's in the alternative allele field.

**Comment by kaeldai** [comment]
In the BCF generated by SAMtools, an non-ref base 'X' represents an base has not been seen from the alignment data. Such a base is necessary to evaluate the probability of missing a non-ref allele due to sampling fluctuation.

**Comment by kaeldai** [comment]
htslib parses 'X' and '<X>' in the ALT fields. However the denovogear code is causing segmentation faults. I'm still investigating, but it appears to happen because in matrix.h it assumes that there are 16 possible genotype combinations and doesn't take into account a possible X allele. 

More importantly, call doesn't handle 'N' in the ALT allele for the same reason.

**Comment by reedacartwright** [comment]
@maip How close are we to getting a pull request?

**Comment by maip** [comment]
I'll try and get that in by Friday.
